=== kmafeni04/registry/schemas/registry.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"required": ["name", "git", "versions"],
	"properties": {
		"name": {
			"type": "string",
			"pattern": "^(?:[a-z][a-z0-9_-]{1,}[a-z0-9]/)?[a-z](?:[a-z0-9_-]*[a-z0-9])?$",
			"maxLength": 128
		},
		"description": {
			"type": "string"
		},
		"license": {
			"type": "string"
		},
		"authors": {
			"type": "array",
			"items": { "type": "string" }
		},
		"git": {
			"type": "string",
			"format": "uri"
		},
		"branch": {
			"type": "string",
			"default": "main"
		},
		"versions": {
			"type": "object",
			"additionalProperties": {
				"type": "string",
				"description": "Commit hash for this version"
			},
			"minProperties": 1
		},
		"dependencies": {
			"type": "object",
			"additionalProperties": {
				"type": "string",
				"description": "Version constraint"
			}
		}
	},
	"additionalProperties": false
}

=== kmafeni04/registry/packages/lua-sys.json
{
	"name": "lua-sys",
	"description": "LuaJIT C api bindings for lde.",
	"authors": [
		"David Cruz <david@bycruz.dev>"
	],
	"git": "https://github.com/lde-org/lua-sys.git",
	"branch": "master",
	"versions": {
		"0.1.0": "9246e262d0388a744ebe2aa838fdf8a552d67755",
		"0.1.1": "3a9a1b1f2b18ca9cd029b66ae8935a60c208695b",
		"0.1.2": "0b9985bc6b23f51bc7a27f6b1c5ac390d14e20eb",
		"0.1.3": "1fcf706087f4ea7b9dced8a483315d2a02393576",
		"0.1.4": "e5c76eab9ca44ca906e05b8749809372beac05e1"
	}
}

=== kmafeni04/registry/packages/ssdg.json
{
	"name": "ssdg",
	"description": "A language agnostic documentation generator written",
	"authors": [
		"Leonard Mafeni <komemafeni944@gmail.com>"
	],
	"git": "https://codeberg.org/kmafeni04/ssdg.git",
	"branch": "main",
	"versions": {
		"0.2.3": "825e8554564248cf6c40a96e8913ce6775d19435",
		"0.3.0": "b1cfebb5fe94ba154201a934d22f3d40f4b58697",
		"0.3.1": "f1c2c0c1839ea2418941142bba9aa12a97a0c9b7",
		"0.3.2": "ea9d1abb1ece96fa166f8040066b408af50236f7",
		"0.3.3": "a2688a0bffd87bea60a3b8058e9c49349fdda94c",
		"0.3.4": "b34dc9f719aab0e568f21f283c124e37569fac65",
		"0.3.5": "439014c2dd9b47476425a3dd54f24faf32db6052",
		"0.3.6": "e437635c078e6545de2f8a32d4a7df61bdd66a83"
	}
}

=== kmafeni04/registry/packages/json.json
{
	"name": "json",
	"description": "JSON(5) encoding and decoding for lde, backed by yyjson.",
	"authors": [
		"David Cruz <david@bycruz.dev>"
	],
	"git": "https://github.com/lde-org/json.git",
	"branch": "master",
	"versions": {
		"0.1.0": "05d08771500ed909a8022b68f98e0c698acf53fc",
		"0.1.1": "2fea69eede30788e33a436c60784c4790eb74105"
	}
}

=== kmafeni04/registry/packages/tltp.json
{
	"name": "tltp",
	"description": "A Teal/LuaJIT HTTP/1.1 web server library",
	"authors": [
		"Leonard Mafeni <komemafeni944@gmail.com>"
	],
	"git": "https://codeberg.org/kmafeni04/tltp.git",
	"branch": "main",
	"versions": {
		"0.1.0": "af639f410282cea7f6f362fd8e1d24e773127353",
		"0.2.0": "ba18a31c85628a320ad02efa3462536f034448da",
		"0.3.0": "108dd1d793cad6cb7a9f025a75be5a3b66760a79",
		"0.3.1": "e3c26cc1d25d3442583669fc7086b12be714bfa8",
		"0.3.2": "13fa639e67b7e8ca695fb002ed6ab1323b6efe4e",
		"0.3.3": "6d48ce9d039783ba19b8fd5de5e65ec4d99b36b1"
	}
}

=== kmafeni04/registry/packages/targs.json
{
	"name": "targs",
	"description": "A command line argument parser for lua and teal",
	"authors": [
		"Leonard Mafeni <komemafeni944@gmail.com>"
	],
	"git": "https://codeberg.org/kmafeni04/targs.git",
	"branch": "main",
	"versions": {
		"0.4.0": "0467aa3fa40ccbf3af55392ea135401e4e4a990e",
		"0.4.1": "553e3e866a60253c4c204bc707b8198f90cc3d48",
		"0.4.2": "5f2f43ac32ed70cd1b3fabb99be05701b4001a89",
		"0.4.3": "0fb510b8e78cadfb429d87687641391dc6a17d9a",
		"0.4.4": "4923bd00596b2f389f3c130fb96f3a91f29d6d58",
		"0.4.5": "3d71275b005c7df0867fe170003ee19c0fb2b887",
		"0.5.0": "47bc65aa4dabbcc2c993813a74fcbd9701927881"
	}
}
