=== kmafeni04/registry/schemas/registry.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"required": ["name", "git", "versions"],
	"properties": {
		"name": {
			"type": "string",
			"pattern": "^(?:[a-z][a-z0-9_-]{1,}[a-z0-9]/)?[a-z](?:[a-z0-9_-]*[a-z0-9])?$",
			"maxLength": 128
		},
		"description": {
			"type": "string"
		},
		"license": {
			"type": "string"
		},
		"authors": {
			"type": "array",
			"items": { "type": "string" }
		},
		"git": {
			"type": "string",
			"format": "uri"
		},
		"branch": {
			"type": "string",
			"default": "main"
		},
		"versions": {
			"type": "object",
			"additionalProperties": {
				"type": "string",
				"description": "Commit hash for this version"
			},
			"minProperties": 1
		},
		"dependencies": {
			"type": "object",
			"additionalProperties": {
				"type": "string",
				"description": "Version constraint"
			}
		}
	},
	"additionalProperties": false
}

=== kmafeni04/registry/packages/fs.json
{
	"name": "fs",
	"description": "A cross platform fs library for lde.",
	"authors": [
		"David Cruz <david@bycruz.dev>"
	],
	"git": "https://github.com/lde-org/fs.git",
	"branch": "master",
	"versions": {
		"0.1.0": "bc8342a49d667b807152ac95191f3818035d1a48",
		"0.2.0": "7babb8f41184dc80834fbf55a5528f39d6df111e",
		"0.2.1": "c52fd12402518db5a1f41f4a189b8376261790d9",
		"0.3.0": "54160bc07dd1afedbf449843f1564bfbd6b82960"
	}
}

=== kmafeni04/registry/packages/archive.json
{
	"name": "archive",
	"description": "Archive extraction and creation library. Supports zip and tar.",
	"authors": [
		"David Cruz <david@bycruz.dev>"
	],
	"git": "https://github.com/lde-org/archive.git",
	"branch": "master",
	"versions": {
		"0.1.0": "fffd1657ec146b136f4416a297faa6af59ebeeaa"
	}
}

=== kmafeni04/registry/packages/fstrings.json
{
	"name": "fstrings",
	"description": "Adding string interpolation to lua",
	"authors": [
		"Leonard Mafeni <komemafeni944@gmail.com>"
	],
	"git": "https://codeberg.org/kmafeni04/fstrings-lua.git",
	"branch": "main",
	"versions": {
		"0.1.1": "86cae053f453ab52b38f74342277ddbb4305fd36",
		"0.2.0": "05805a1ad28bf4e7b295a4d8e12be2fe1e6a9563"
	}
}

=== kmafeni04/registry/packages/sstream.json
{
	"name": "sstream",
	"description": "A library to compose strings",
	"authors": [
		"Leonard Mafeni <komemafeni944@gmail.com>"
	],
	"git": "https://codeberg.org/kmafeni04/sstream-lua.git",
	"branch": "main",
	"versions": {
		"0.1.2": "383499688dbec7ba1ecc7d341887459ad76ea1f7",
		"0.1.3": "ec24b21b6292250f853bfaa3a7a043f9dbef1414",
		"0.1.4": "d03e6ecfc43693fce12239eb40cf7bfb61089099"
	}
}

=== kmafeni04/registry/packages/cowsay.json
{
	"name": "cowsay",
	"description": "A cow that says things",
	"authors": [
		"David Cruz <david@bycruz.dev>"
	],
	"git": "https://github.com/bycruz/cowsay.git",
	"branch": "master",
	"versions": {
		"0.1.0": "d8a5f0a74a90f3dc20f907d18dc13ec8dc57cd9a",
		"0.2.0": "de1ae8bfda94359608cdda0364631f382b5b39c1"
	}
}

=== kmafeni04/registry/packages/process.json
{
	"name": "process",
	"description": "A cross platform process library for lde.",
	"authors": [
		"David Cruz <david@bycruz.dev>"
	],
	"git": "https://github.com/lde-org/process.git",
	"branch": "master",
	"versions": {
		"0.1.0": "fd521a4e7df864a4f17e79e8485991c0a3eddc77",
		"0.1.1": "663eaa993131750081f544df4e50a125ea4970ef"
	}
}

=== kmafeni04/registry/packages/socket.json
{
	"name": "socket",
	"description": "A cross platform socket library.",
	"authors": [
		"David Cruz <david@bycruz.dev>"
	],
	"git": "https://github.com/lde-org/socket.git",
	"branch": "master",
	"versions": {
		"0.1.0": "390ae5651500cb250a155ae7c682c5cdbec15fb4",
		"0.1.1": "459c9baf3f02a2b1b762a097ac51cbd0ef420080",
		"0.3.0": "95b50b3bd7317bd0522cf9f048440ed7334b0978"
	}
}

=== kmafeni04/registry/packages/tilt.json
{
	"name": "tilt",
	"description": "A simple templating engine for lua and teal",
	"authors": [
		"Leonard Mafeni <komemafeni944@gmail.com>"
	],
	"git": "https://codeberg.org/kmafeni04/tilt.git",
	"branch": "main",
	"versions": {
		"0.1.0": "f53703b11c349b5bce24f5b56c4b5ca3d1a5d0bc",
        "0.1.1": "51684575ed1b441a3175011348f022b56ee06c5c",
		"0.1.2": "3b717d2bcd8f73dd209b8c790ea410b584cf5715"
	}
}
